export const vehiclesType = [
  { value: '', title: 'Selecione' },
  { value: 'Ambulancia', title: 'Ambulância' },
  { value: 'Barco', title: 'Barco' },
  { value: 'Bitrem', title: 'Bitrem' },
  { value: 'Carro', title: 'Carro' },
  { value: 'Caminhao', title: 'Caminhão' },
  { value: 'Caminhonete', title: 'Caminhonete' },
  { value: 'Caminhao_Betoneira', title: 'Caminhão Betoneira' },
  { value: 'Caminhao_Pipa', title: 'Caminhão Pipa' },
  { value: 'Colheitadeira', title: 'Colheitadeira' },
  { value: 'Escavadeira', title: 'Escavadeira' },
  { value: 'Moto', title: 'Moto' },
  { value: 'Motobomba', title: 'Motobomba' },
  { value: 'Motoniveladora', title: 'Motoniveladora' },
  { value: 'Onibus', title: 'Ônibus' },
  { value: 'Pa_Carregadora', title: 'Pá Carregadora' },
  { value: 'Pessoa', title: 'Pessoa' },
  { value: 'Semaforo', title: 'Semáforo' },
  { value: 'Trator', title: 'Trator' },
  { value: 'Trator_de_Esteira', title: 'Trator de Esteira' },
  { value: 'Outras', title: 'Outros' },
]

export const vehiclesColor = [
  { value: '', title: 'Selecione' },
  { value: 'AMARELO', title: 'AMARELO' },
  { value: 'AZUL', title: 'AZUL' },
  { value: 'BEGE', title: 'BEGE' },
  { value: 'BRANCA', title: 'BRANCA' },
  { value: 'CINZA', title: 'CINZA' },
  { value: 'DOURADA', title: 'DOURADA' },
  { value: 'GRENA', title: 'GRENA' },
  { value: 'LARANJA', title: 'LARANJA' },
  { value: 'MARROM', title: 'MARROM' },
  { value: 'PRATA', title: 'PRATA' },
  { value: 'PRETA', title: 'PRETA' },
  { value: 'ROSA', title: 'ROSA' },
  { value: 'ROXA', title: 'ROXA' },
  { value: 'VERDE', title: 'VERDE' },
  { value: 'VERMELHA', title: 'VERMELHA' },
  { value: 'FANTASIA', title: 'FANTASIA' },
]
