import { Location, MobileOperator, Model, Timezone, Vehicle } from '../models'

const location: Location = {
  active: true,
  cellId: '',
  course: '',
  createAt: new Date(Date.now()),
  deleted: false,
  deviceId: '',
  fixTime: new Date(),
  id: '',
  lac: 0,
  latitude: -3.8580372,
  longitude: -38.495503,
  mcc: 0,
  mnc: 0,
  satellite: 0,
  serverTime: new Date(Date.now()),
  speed: 0,
  updateAt: new Date(Date.now()),
}

export const zeroCenter: Vehicle = {
  active: true,
  branchId: '',
  brand: '',
  chassi: '',
  color: '',
  createAt: new Date(Date.now()).toISOString(),
  customerId: '',
  deleted: false,
  deviceId: '',
  id: '',
  licensePlate: '',
  model: '',
  observation: '',
  renavam: '',
  type: '',
  updateAt: new Date(Date.now()).toISOString(),
  year: new Date(Date.now()).getFullYear(),
  device: {
    location: [location],
    active: true,
    alert: [],
    chipNumber: '',
    code: 0,
    createAt: new Date().toISOString(),
    deleted: false,
    description: '',
    equipmentNumber: '',
    id: '',
    mobileOperator: MobileOperator.Outras,
    model: Model.GT06,
    note: '',
    phone: '',
    status: [],
    timezone: Timezone.GMT_3,
    updateAt: new Date().toISOString(),
  },
}
